// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1i0jMrfe8NsqdpEhWng7CJudwp3CQmzs',
    appId: '1:720308364628:web:7a996ab95b5ee8d7fad4c1',
    messagingSenderId: '720308364628',
    projectId: 'nohunger-a3827',
    authDomain: 'nohunger-a3827.firebaseapp.com',
    storageBucket: 'nohunger-a3827.firebasestorage.app',
    measurementId: 'G-EESLLQS5CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPaXS0tQK7PGxOWIFu6FAfBM7ShGCPWX0',
    appId: '1:720308364628:android:7ad7f25d954f5312fad4c1',
    messagingSenderId: '720308364628',
    projectId: 'nohunger-a3827',
    storageBucket: 'nohunger-a3827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnbvR0idXL-of-MF4KuEmHKC6Qm1lP_Ss',
    appId: '1:720308364628:ios:15a760e18bb467e7fad4c1',
    messagingSenderId: '720308364628',
    projectId: 'nohunger-a3827',
    storageBucket: 'nohunger-a3827.firebasestorage.app',
    iosBundleId: 'com.example.nohunger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnbvR0idXL-of-MF4KuEmHKC6Qm1lP_Ss',
    appId: '1:720308364628:ios:15a760e18bb467e7fad4c1',
    messagingSenderId: '720308364628',
    projectId: 'nohunger-a3827',
    storageBucket: 'nohunger-a3827.firebasestorage.app',
    iosBundleId: 'com.example.nohunger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1i0jMrfe8NsqdpEhWng7CJudwp3CQmzs',
    appId: '1:720308364628:web:c9e6b3e478d6929efad4c1',
    messagingSenderId: '720308364628',
    projectId: 'nohunger-a3827',
    authDomain: 'nohunger-a3827.firebaseapp.com',
    storageBucket: 'nohunger-a3827.firebasestorage.app',
    measurementId: 'G-PTWDR9V8JH',
  );
}
